; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.39"

; Modules
projects[admin_menu][version] = "3.0-rc5"

projects[backup_migrate][version] = "2.8"

projects[block_class][version] = "2.1"

projects[blockify][version] = "1.2"

projects[ctools][version] = "1.9"

projects[calendar][version] = "3.5"

projects[date][version] = "2.9"

projects[devel][version] = "1.5"

projects[draggableviews][version] = "2.1"

projects[entity][version] = "1.6"

projects[field_formatter_settings][version] = "1.1"

projects[i18n][version] = "1.13"

projects[image_class][version] = "1.0"

projects[imageblock][version] = "1.3"

projects[insert][version] = "1.3"

projects[jquery_plugin][version] = "1.0"

projects[libraries][version] = "2.2"

projects[pathauto][version] = "1.3"

projects[token][version] = "1.6"

projects[variable][version] = "2.5"

projects[views][version] = "3.11"

projects[views_slideshow][version] = "3.1"

projects[webform][version] = "3.24"

projects[wysiwyg][version] = "2.2"

; Themes
projects[business][version] = "1.11"

projects[business_responsive_theme][version] = "2.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[“phil_subtheme”][download][type] = "git"
projects[“phil_subtheme”][download][url] = "https://github.com/philkrie/business_subtheme.git"
projects[“phil_subtheme”][type] = "theme"
projects[“phil_subtheme”][version] = "1.11"

projects[uobanner][download][type] = “get”
projects[uobanner][download][url] = "http://it.uoregon.edu/system/files/uobanner_v1.5.zip"
projects[uobanner][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.6.1/ckeditor_3.6.6.1.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"
 
libraries[json2][type] = "library"
libraries[json2][download][type] = "file"
libraries[json2][download][url] = "https://raw.githubusercontent.com/douglascrockford/JSON-js/master/json2.js"
 
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = "file"
libraries[jquery.cycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

