; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[drupal][version] = "7.38"

; Modules
projects[backup_migrate][version] = "2.8"

projects[blockify][version] = "1.2"

projects[ctools][version] = "1.7"

projects[calendar][version] = "3.4"

projects[date][version] = "2.8"

projects[draggableviews][version] = "2.0"

projects[entity][version] = "1.6"

projects[i18n][version] = "1.11"

projects[insert][version] = "1.3"

projects[jquery_plugin][version] = "1.0"

projects[libraries][version] = "2.2"

projects[pathauto][version] = "1.2"

projects[token][version] = "1.5"

projects[variable][version] = "2.5"

projects[views][version] = "3.11"

; projects[views_slideshow][version] = "3.1" - added to git because module has embedded makefile

projects[webform][version] = "3.23"

projects[wysiwyg][version] = "2.2"

; Themes
projects[business][version] = "1.11"

projects[business_responsive_theme][version] = "2.0"

; Modules
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
; uobanner
projects[uobanner][download][type] = "git"
projects[uobanner][download][url] = "https://git.uoregon.edu/scm/uo_drpl_prod/uobanner.git" 
projects[uobanner][type] = "module"

; views_slideshow-nomake
projects[views_slideshow-nomake][download][type] = "git"
projects[views_slideshow-nomake][download][url] = "ssh://git@git.uoregon.edu/asdm/views_slideshow-nomake.git" 
projects[views_slideshow-nomake][type] = "module"
; projects[views_slideshow-nomake][download][tag] = 7.x-1.3

; Libraries
; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.6.1/ckeditor_3.6.6.1.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

libraries[json2][type] = "library"
libraries[json2][download][type] = "file"
libraries[json2][download][url] = "https://raw.githubusercontent.com/douglascrockford/JSON-js/master/json2.js"

; Please fill the following out. Type may be one of get, cvs, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = "file"
libraries[jquery.cycle][download][url] = "http://malsup.github.com/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"
